export const LOADING_QUOTES = 'App/LOADING_QUOTES';
export const LOADED_QUOTES = 'App/LOADED_QUOTES';
export const LOADING_RANDOM_QUOTE = 'App/LOADING_RANDOM_QUOTE';
export const LOADED_RANDOM_QUOTE = 'App/LOADED_RANDOM_QUOTE';